### ISSUE TITLE
Toys Guix Channel Search

### ISSUE THREAD

**Issue by jgarte** [umanwizard/pkgs#1]
Hi fellow Guixer,

Would you be interested in joining our Guix channel search engine?

https://toys.whereis.みんな/

If so, send a patch here adding your channel:

https://git.sr.ht/~whereiseveryone/toys#join

**Comment by umanwizard** [comment]
Your site is down: "502 bad gateway".

Also, I don't know how to type "みんな" without copying and pasting. If you want non-Japanese people to be able to use your site, I suggest moving it to a more traditional TLD.
